### ISSUE TITLE
Why can't I run it Bitmancer

### ISSUE THREAD

**Issue by cherchis42** [zimawhit3/Bitmancer#12]
After I tried a  options

```
nimble install https://github.com/zimawhit3/Bitmancer
nimble refresh
nimble search Bitmancer --ver
```
output
![image](https://user-images.githubusercontent.com/114790811/197318466-2e43be7a-dcff-4219-85b6-b96af3484aea.png)

**Comment by zimawhit3** [comment]
should be fixed now
